# The URL the site will be built for
base_url = "https://idunnowhatiamdoing.engineering"
title = "i dunno what i am doing"
description = "Software engineering à la Mexicana"
default_language = "en"
theme = "void"
output_dir = "public"
compile_sass = true
minify_html = false # Keep this false, as it may cause issues with some styles
build_search_index = false # Keep this false, search is temporarily unsupported
generate_feeds = false # Whether to generate a feed file in root, read docs for more info about rss feed
feed_filenames = ["feed.xml"] # "feed.xml" | "atom.xml" | "rss.xml", read docs for more info
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["themes/void/highlight_themes"]
highlight_themes_css = [
  { theme = "void-light", filename = "hl-light.css" },
  { theme = "void-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

sections = [
  { name = "posts", path = "/posts", is_external = false },
  { name = "projects", path = "/projects", is_external = false },
  { name = "about", path = "/about", is_external = false },
  # { name = "tags", path = "/tags", is_external = false },
  # { name = "github", path = "https://github.com/<your-username>", is_external = true },
]

blog_section_path = "/posts"

back_link_text = "back" # Text of the back button
force_theme = "light" # false | "light" | "dark"

footer_copyright = "∅ 2026 n0um3n4"
footer_credits = false # Whether to show "Built with zola and serene" in footer

not_found_error_text = "404 Ain't Found No Mo'e"
not_found_recover_text = "« back to home »"

reaction = false # Whether to enable anonymous emoji reactions (Note: You need to set up a working api endpoint to enable this feature)
reaction_align = "right" # "left" | "center" | "right"
reaction_endpoint = "https://example.com/api/reaction"
